name: Build and upload artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install 
      - name: Upload Artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: Spring-Boot-Azure
          path: '${{ github.workspace }}/target/*.jar'
 
