name: Build and upload artifacts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Upload Artifacct for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: springboot-example
          path: ${{ github.workspace }}/target/*.jar
