name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build project
        run: mvn clean install -DskipTests  # Added hyphen
      - name: upload Artifacts for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: springboot-example
          path: /target/*.jar  # Removed github.workspace
