name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: springboot-example
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: springboot-app-test
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'
