name: Deploy to Azure Web App

on:
  workflow_run:  # Triggered when the first workflow successfully completes 
    workflows: ["Build and upload artifacts"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: Spring-Boot-Azure
  
      - name: Deploy to Azure App Service
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: my-app
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: 'app.jar'
          
