name: Deploy to Azure Web App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs:  build
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: springboot-example
          path: ${{ github.workspace }}/target/*.jar
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: Spring-java-APP
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'
          
