name: Deploy to Azure Web App

on:
  workflow_run:  # Triggered when the first workflow successfully completes 
    workflows: ["Build and upload artifacts"]
    types: 
      - completed

jobs:
 deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts from build workflows
        uses: actions/download-artifact@v4
        with:
          name: springboot-example  # Replace with the name of the artifact created in your build job
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
       
          
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: Spring-java-APP
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: 'target/*.jar'

