name: Deploy to Azure Web App

on:
  workflow_run:  # Triggered when the first workflow successfully completes 
    workflows: ["Build and upload artifacts"]
    types: 
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: artifact-app
  
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: Spring-java-APP
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: '*.jar'
          
